# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.permissions_api import PermissionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self):
        self.api = PermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_access_permissions(self):
        """Test case for get_access_permissions

        Get access permissions  # noqa: E501
        """
        pass

    def test_get_page_permissions(self):
        """Test case for get_page_permissions

        Get page permissions  # noqa: E501
        """
        pass

    def test_get_role_permissions(self):
        """Test case for get_role_permissions

        Update userrole permissions  # noqa: E501
        """
        pass

    def test_get_role_permissions1(self):
        """Test case for get_role_permissions1

        Get userrole permissions  # noqa: E501
        """
        pass

    def test_get_role_permissions2(self):
        """Test case for get_role_permissions2

        Get userrole permissions  # noqa: E501
        """
        pass

    def test_update_access_permissions(self):
        """Test case for update_access_permissions

        Update access permissions  # noqa: E501
        """
        pass

    def test_update_device_group_permissions(self):
        """Test case for update_device_group_permissions

        Update deviceGroup permissions  # noqa: E501
        """
        pass

    def test_update_device_group_permissions1(self):
        """Test case for update_device_group_permissions1

        Get deviceGroup permissions  # noqa: E501
        """
        pass

    def test_update_device_group_permissions2(self):
        """Test case for update_device_group_permissions2

        Get deviceGroup permissions  # noqa: E501
        """
        pass

    def test_update_page_permissions(self):
        """Test case for update_page_permissions

        Update page permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
