# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.indicatortypes_filter_body import IndicatortypesFilterBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIndicatortypesFilterBody(unittest.TestCase):
    """IndicatortypesFilterBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndicatortypesFilterBody(self):
        """Test IndicatortypesFilterBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.indicatortypes_filter_body.IndicatortypesFilterBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
