# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.flow_falcon_template_setting_v1 import FlowFalconTemplateSettingV1  # noqa: E501
from swagger_client.rest import ApiException


class TestFlowFalconTemplateSettingV1(unittest.TestCase):
    """FlowFalconTemplateSettingV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowFalconTemplateSettingV1(self):
        """Test FlowFalconTemplateSettingV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.flow_falcon_template_setting_v1.FlowFalconTemplateSettingV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
