# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.maintenance_windows_api import MaintenanceWindowsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMaintenanceWindowsApi(unittest.TestCase):
    """MaintenanceWindowsApi unit test stubs"""

    def setUp(self):
        self.api = MaintenanceWindowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_maintenance_window(self):
        """Test case for create_maintenance_window

        Create maintenance window associated with devices  # noqa: E501
        """
        pass

    def test_create_maintenance_window1(self):
        """Test case for create_maintenance_window1

        Create maintenance window associated to device groups  # noqa: E501
        """
        pass

    def test_delete_maintenance_window_by_id(self):
        """Test case for delete_maintenance_window_by_id

        Delete maintenance window  # noqa: E501
        """
        pass

    def test_filter_maintenance_windows(self):
        """Test case for filter_maintenance_windows

        Get filtered list of maintenance windows of any entity type  # noqa: E501
        """
        pass

    def test_filter_maintenance_windows1(self):
        """Test case for filter_maintenance_windows1

        Get filtered list of device maintenance windows  # noqa: E501
        """
        pass

    def test_get_maintenance_window_by_id(self):
        """Test case for get_maintenance_window_by_id

        Get maintenance window  # noqa: E501
        """
        pass

    def test_get_maintenance_windows(self):
        """Test case for get_maintenance_windows

        Get list of maintenance windows  # noqa: E501
        """
        pass

    def test_update_group_maintenance_window(self):
        """Test case for update_group_maintenance_window

        """
        pass

    def test_update_maintenance_window_by_id(self):
        """Test case for update_maintenance_window_by_id

        Update maintenance window associated with devices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
