# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.report_attachments_topology_api import ReportAttachmentsTopologyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportAttachmentsTopologyApi(unittest.TestCase):
    """ReportAttachmentsTopologyApi unit test stubs"""

    def setUp(self):
        self.api = ReportAttachmentsTopologyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_topology_attachment(self):
        """Test case for create_topology_attachment

        Create topology attachment  # noqa: E501
        """
        pass

    def test_get_topology_attachment(self):
        """Test case for get_topology_attachment

        Get topology attachment  # noqa: E501
        """
        pass

    def test_get_topology_attachment_filters(self):
        """Test case for get_topology_attachment_filters

        Get attachment topology filters  # noqa: E501
        """
        pass

    def test_get_topology_attachment_resources(self):
        """Test case for get_topology_attachment_resources

        Get resources  # noqa: E501
        """
        pass

    def test_get_topology_attachment_settings(self):
        """Test case for get_topology_attachment_settings

        Get attachment settings  # noqa: E501
        """
        pass

    def test_get_topology_attachment_visualization_settings(self):
        """Test case for get_topology_attachment_visualization_settings

        Get attachment visualization settings  # noqa: E501
        """
        pass

    def test_partial_update_topology_attachment_settings(self):
        """Test case for partial_update_topology_attachment_settings

        Partial update attachment settings  # noqa: E501
        """
        pass

    def test_update_topology_attachment_filters(self):
        """Test case for update_topology_attachment_filters

        Update topology filters  # noqa: E501
        """
        pass

    def test_update_topology_attachment_resources(self):
        """Test case for update_topology_attachment_resources

        Update resources  # noqa: E501
        """
        pass

    def test_update_topology_attachment_settings(self):
        """Test case for update_topology_attachment_settings

        Update attachment settings  # noqa: E501
        """
        pass

    def test_update_topology_attachment_visualization_settings(self):
        """Test case for update_topology_attachment_visualization_settings

        Update visualization settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
