# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeviceDiscoveryFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_filter': 'DeviceFilter',
        'allow_automatic': 'bool',
        'allow_manual': 'bool',
        'queue_in': 'list[str]',
        'is_working': 'bool',
        'time_queued_between': 'PairLongLong',
        'time_updated_between': 'PairLongLong',
        'time_started_between': 'PairLongLong',
        'time_completed_between': 'PairLongLong',
        'times_discovered_between': 'PairLongLong'
    }

    attribute_map = {
        'device_filter': 'deviceFilter',
        'allow_automatic': 'allowAutomatic',
        'allow_manual': 'allowManual',
        'queue_in': 'queueIn',
        'is_working': 'isWorking',
        'time_queued_between': 'timeQueuedBetween',
        'time_updated_between': 'timeUpdatedBetween',
        'time_started_between': 'timeStartedBetween',
        'time_completed_between': 'timeCompletedBetween',
        'times_discovered_between': 'timesDiscoveredBetween'
    }

    def __init__(self, device_filter=None, allow_automatic=None, allow_manual=None, queue_in=None, is_working=None, time_queued_between=None, time_updated_between=None, time_started_between=None, time_completed_between=None, times_discovered_between=None):  # noqa: E501
        """DeviceDiscoveryFilter - a model defined in Swagger"""  # noqa: E501
        self._device_filter = None
        self._allow_automatic = None
        self._allow_manual = None
        self._queue_in = None
        self._is_working = None
        self._time_queued_between = None
        self._time_updated_between = None
        self._time_started_between = None
        self._time_completed_between = None
        self._times_discovered_between = None
        self.discriminator = None
        if device_filter is not None:
            self.device_filter = device_filter
        if allow_automatic is not None:
            self.allow_automatic = allow_automatic
        if allow_manual is not None:
            self.allow_manual = allow_manual
        if queue_in is not None:
            self.queue_in = queue_in
        if is_working is not None:
            self.is_working = is_working
        if time_queued_between is not None:
            self.time_queued_between = time_queued_between
        if time_updated_between is not None:
            self.time_updated_between = time_updated_between
        if time_started_between is not None:
            self.time_started_between = time_started_between
        if time_completed_between is not None:
            self.time_completed_between = time_completed_between
        if times_discovered_between is not None:
            self.times_discovered_between = times_discovered_between

    @property
    def device_filter(self):
        """Gets the device_filter of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The device_filter of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: DeviceFilter
        """
        return self._device_filter

    @device_filter.setter
    def device_filter(self, device_filter):
        """Sets the device_filter of this DeviceDiscoveryFilter.


        :param device_filter: The device_filter of this DeviceDiscoveryFilter.  # noqa: E501
        :type: DeviceFilter
        """

        self._device_filter = device_filter

    @property
    def allow_automatic(self):
        """Gets the allow_automatic of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The allow_automatic of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: bool
        """
        return self._allow_automatic

    @allow_automatic.setter
    def allow_automatic(self, allow_automatic):
        """Sets the allow_automatic of this DeviceDiscoveryFilter.


        :param allow_automatic: The allow_automatic of this DeviceDiscoveryFilter.  # noqa: E501
        :type: bool
        """

        self._allow_automatic = allow_automatic

    @property
    def allow_manual(self):
        """Gets the allow_manual of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The allow_manual of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: bool
        """
        return self._allow_manual

    @allow_manual.setter
    def allow_manual(self, allow_manual):
        """Sets the allow_manual of this DeviceDiscoveryFilter.


        :param allow_manual: The allow_manual of this DeviceDiscoveryFilter.  # noqa: E501
        :type: bool
        """

        self._allow_manual = allow_manual

    @property
    def queue_in(self):
        """Gets the queue_in of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The queue_in of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._queue_in

    @queue_in.setter
    def queue_in(self, queue_in):
        """Sets the queue_in of this DeviceDiscoveryFilter.


        :param queue_in: The queue_in of this DeviceDiscoveryFilter.  # noqa: E501
        :type: list[str]
        """

        self._queue_in = queue_in

    @property
    def is_working(self):
        """Gets the is_working of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The is_working of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: bool
        """
        return self._is_working

    @is_working.setter
    def is_working(self, is_working):
        """Sets the is_working of this DeviceDiscoveryFilter.


        :param is_working: The is_working of this DeviceDiscoveryFilter.  # noqa: E501
        :type: bool
        """

        self._is_working = is_working

    @property
    def time_queued_between(self):
        """Gets the time_queued_between of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The time_queued_between of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: PairLongLong
        """
        return self._time_queued_between

    @time_queued_between.setter
    def time_queued_between(self, time_queued_between):
        """Sets the time_queued_between of this DeviceDiscoveryFilter.


        :param time_queued_between: The time_queued_between of this DeviceDiscoveryFilter.  # noqa: E501
        :type: PairLongLong
        """

        self._time_queued_between = time_queued_between

    @property
    def time_updated_between(self):
        """Gets the time_updated_between of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The time_updated_between of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: PairLongLong
        """
        return self._time_updated_between

    @time_updated_between.setter
    def time_updated_between(self, time_updated_between):
        """Sets the time_updated_between of this DeviceDiscoveryFilter.


        :param time_updated_between: The time_updated_between of this DeviceDiscoveryFilter.  # noqa: E501
        :type: PairLongLong
        """

        self._time_updated_between = time_updated_between

    @property
    def time_started_between(self):
        """Gets the time_started_between of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The time_started_between of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: PairLongLong
        """
        return self._time_started_between

    @time_started_between.setter
    def time_started_between(self, time_started_between):
        """Sets the time_started_between of this DeviceDiscoveryFilter.


        :param time_started_between: The time_started_between of this DeviceDiscoveryFilter.  # noqa: E501
        :type: PairLongLong
        """

        self._time_started_between = time_started_between

    @property
    def time_completed_between(self):
        """Gets the time_completed_between of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The time_completed_between of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: PairLongLong
        """
        return self._time_completed_between

    @time_completed_between.setter
    def time_completed_between(self, time_completed_between):
        """Sets the time_completed_between of this DeviceDiscoveryFilter.


        :param time_completed_between: The time_completed_between of this DeviceDiscoveryFilter.  # noqa: E501
        :type: PairLongLong
        """

        self._time_completed_between = time_completed_between

    @property
    def times_discovered_between(self):
        """Gets the times_discovered_between of this DeviceDiscoveryFilter.  # noqa: E501


        :return: The times_discovered_between of this DeviceDiscoveryFilter.  # noqa: E501
        :rtype: PairLongLong
        """
        return self._times_discovered_between

    @times_discovered_between.setter
    def times_discovered_between(self, times_discovered_between):
        """Sets the times_discovered_between of this DeviceDiscoveryFilter.


        :param times_discovered_between: The times_discovered_between of this DeviceDiscoveryFilter.  # noqa: E501
        :type: PairLongLong
        """

        self._times_discovered_between = times_discovered_between

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceDiscoveryFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceDiscoveryFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
