# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IndicatorDtoIncludeMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'device_id': 'int',
        'object_id': 'int',
        'plugin_id': 'int',
        'plugin_indicator_type_id': 'int',
        'name': 'str',
        'description': 'str',
        'data_units': 'str',
        'display_units': 'str',
        'is_enabled': 'bool',
        'is_baselining': 'bool',
        'is_deleted': 'bool',
        'max_value': 'float',
        'system_max_value': 'float',
        'first_seen': 'int',
        'last_seen': 'int',
        'system_is_enabled': 'bool',
        'system_is_baselining': 'bool',
        'format': 'str',
        'last_invalidation_time': 'int',
        'synthetic_expression': 'str',
        'evaluation_order': 'int',
        'extended_info': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'id',
        'device_id': 'deviceId',
        'object_id': 'objectId',
        'plugin_id': 'pluginId',
        'plugin_indicator_type_id': 'pluginIndicatorTypeId',
        'name': 'name',
        'description': 'description',
        'data_units': 'dataUnits',
        'display_units': 'displayUnits',
        'is_enabled': 'isEnabled',
        'is_baselining': 'isBaselining',
        'is_deleted': 'isDeleted',
        'max_value': 'maxValue',
        'system_max_value': 'systemMaxValue',
        'first_seen': 'firstSeen',
        'last_seen': 'lastSeen',
        'system_is_enabled': 'systemIsEnabled',
        'system_is_baselining': 'systemIsBaselining',
        'format': 'format',
        'last_invalidation_time': 'lastInvalidationTime',
        'synthetic_expression': 'syntheticExpression',
        'evaluation_order': 'evaluationOrder',
        'extended_info': 'extendedInfo'
    }

    def __init__(self, id=None, device_id=None, object_id=None, plugin_id=None, plugin_indicator_type_id=None, name=None, description=None, data_units=None, display_units=None, is_enabled=None, is_baselining=None, is_deleted=None, max_value=None, system_max_value=None, first_seen=None, last_seen=None, system_is_enabled=None, system_is_baselining=None, format=None, last_invalidation_time=None, synthetic_expression=None, evaluation_order=None, extended_info=None):  # noqa: E501
        """IndicatorDtoIncludeMetadata - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._device_id = None
        self._object_id = None
        self._plugin_id = None
        self._plugin_indicator_type_id = None
        self._name = None
        self._description = None
        self._data_units = None
        self._display_units = None
        self._is_enabled = None
        self._is_baselining = None
        self._is_deleted = None
        self._max_value = None
        self._system_max_value = None
        self._first_seen = None
        self._last_seen = None
        self._system_is_enabled = None
        self._system_is_baselining = None
        self._format = None
        self._last_invalidation_time = None
        self._synthetic_expression = None
        self._evaluation_order = None
        self._extended_info = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if device_id is not None:
            self.device_id = device_id
        if object_id is not None:
            self.object_id = object_id
        if plugin_id is not None:
            self.plugin_id = plugin_id
        if plugin_indicator_type_id is not None:
            self.plugin_indicator_type_id = plugin_indicator_type_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if data_units is not None:
            self.data_units = data_units
        if display_units is not None:
            self.display_units = display_units
        if is_enabled is not None:
            self.is_enabled = is_enabled
        if is_baselining is not None:
            self.is_baselining = is_baselining
        if is_deleted is not None:
            self.is_deleted = is_deleted
        if max_value is not None:
            self.max_value = max_value
        if system_max_value is not None:
            self.system_max_value = system_max_value
        if first_seen is not None:
            self.first_seen = first_seen
        if last_seen is not None:
            self.last_seen = last_seen
        if system_is_enabled is not None:
            self.system_is_enabled = system_is_enabled
        if system_is_baselining is not None:
            self.system_is_baselining = system_is_baselining
        if format is not None:
            self.format = format
        if last_invalidation_time is not None:
            self.last_invalidation_time = last_invalidation_time
        if synthetic_expression is not None:
            self.synthetic_expression = synthetic_expression
        if evaluation_order is not None:
            self.evaluation_order = evaluation_order
        if extended_info is not None:
            self.extended_info = extended_info

    @property
    def id(self):
        """Gets the id of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IndicatorDtoIncludeMetadata.


        :param id: The id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def device_id(self):
        """Gets the device_id of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The device_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this IndicatorDtoIncludeMetadata.


        :param device_id: The device_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._device_id = device_id

    @property
    def object_id(self):
        """Gets the object_id of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The object_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this IndicatorDtoIncludeMetadata.


        :param object_id: The object_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._object_id = object_id

    @property
    def plugin_id(self):
        """Gets the plugin_id of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The plugin_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._plugin_id

    @plugin_id.setter
    def plugin_id(self, plugin_id):
        """Sets the plugin_id of this IndicatorDtoIncludeMetadata.


        :param plugin_id: The plugin_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._plugin_id = plugin_id

    @property
    def plugin_indicator_type_id(self):
        """Gets the plugin_indicator_type_id of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The plugin_indicator_type_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._plugin_indicator_type_id

    @plugin_indicator_type_id.setter
    def plugin_indicator_type_id(self, plugin_indicator_type_id):
        """Sets the plugin_indicator_type_id of this IndicatorDtoIncludeMetadata.


        :param plugin_indicator_type_id: The plugin_indicator_type_id of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._plugin_indicator_type_id = plugin_indicator_type_id

    @property
    def name(self):
        """Gets the name of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The name of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IndicatorDtoIncludeMetadata.


        :param name: The name of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The description of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this IndicatorDtoIncludeMetadata.


        :param description: The description of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def data_units(self):
        """Gets the data_units of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The data_units of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._data_units

    @data_units.setter
    def data_units(self, data_units):
        """Sets the data_units of this IndicatorDtoIncludeMetadata.


        :param data_units: The data_units of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """

        self._data_units = data_units

    @property
    def display_units(self):
        """Gets the display_units of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The display_units of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._display_units

    @display_units.setter
    def display_units(self, display_units):
        """Sets the display_units of this IndicatorDtoIncludeMetadata.


        :param display_units: The display_units of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """

        self._display_units = display_units

    @property
    def is_enabled(self):
        """Gets the is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled):
        """Sets the is_enabled of this IndicatorDtoIncludeMetadata.


        :param is_enabled: The is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: bool
        """

        self._is_enabled = is_enabled

    @property
    def is_baselining(self):
        """Gets the is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_baselining

    @is_baselining.setter
    def is_baselining(self, is_baselining):
        """Sets the is_baselining of this IndicatorDtoIncludeMetadata.


        :param is_baselining: The is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: bool
        """

        self._is_baselining = is_baselining

    @property
    def is_deleted(self):
        """Gets the is_deleted of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The is_deleted of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_deleted

    @is_deleted.setter
    def is_deleted(self, is_deleted):
        """Sets the is_deleted of this IndicatorDtoIncludeMetadata.


        :param is_deleted: The is_deleted of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: bool
        """

        self._is_deleted = is_deleted

    @property
    def max_value(self):
        """Gets the max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: float
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value):
        """Sets the max_value of this IndicatorDtoIncludeMetadata.


        :param max_value: The max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: float
        """

        self._max_value = max_value

    @property
    def system_max_value(self):
        """Gets the system_max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The system_max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: float
        """
        return self._system_max_value

    @system_max_value.setter
    def system_max_value(self, system_max_value):
        """Sets the system_max_value of this IndicatorDtoIncludeMetadata.


        :param system_max_value: The system_max_value of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: float
        """

        self._system_max_value = system_max_value

    @property
    def first_seen(self):
        """Gets the first_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The first_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this IndicatorDtoIncludeMetadata.


        :param first_seen: The first_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._first_seen = first_seen

    @property
    def last_seen(self):
        """Gets the last_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The last_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this IndicatorDtoIncludeMetadata.


        :param last_seen: The last_seen of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._last_seen = last_seen

    @property
    def system_is_enabled(self):
        """Gets the system_is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The system_is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._system_is_enabled

    @system_is_enabled.setter
    def system_is_enabled(self, system_is_enabled):
        """Sets the system_is_enabled of this IndicatorDtoIncludeMetadata.


        :param system_is_enabled: The system_is_enabled of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: bool
        """

        self._system_is_enabled = system_is_enabled

    @property
    def system_is_baselining(self):
        """Gets the system_is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The system_is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._system_is_baselining

    @system_is_baselining.setter
    def system_is_baselining(self, system_is_baselining):
        """Sets the system_is_baselining of this IndicatorDtoIncludeMetadata.


        :param system_is_baselining: The system_is_baselining of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: bool
        """

        self._system_is_baselining = system_is_baselining

    @property
    def format(self):
        """Gets the format of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The format of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this IndicatorDtoIncludeMetadata.


        :param format: The format of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """
        allowed_values = ["GAUGE", "COUNTER32", "COUNTER64"]  # noqa: E501
        if format not in allowed_values:
            raise ValueError(
                "Invalid value for `format` ({0}), must be one of {1}"  # noqa: E501
                .format(format, allowed_values)
            )

        self._format = format

    @property
    def last_invalidation_time(self):
        """Gets the last_invalidation_time of this IndicatorDtoIncludeMetadata.  # noqa: E501

        Unix timestamp with milliseconds proximity  # noqa: E501

        :return: The last_invalidation_time of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._last_invalidation_time

    @last_invalidation_time.setter
    def last_invalidation_time(self, last_invalidation_time):
        """Sets the last_invalidation_time of this IndicatorDtoIncludeMetadata.

        Unix timestamp with milliseconds proximity  # noqa: E501

        :param last_invalidation_time: The last_invalidation_time of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._last_invalidation_time = last_invalidation_time

    @property
    def synthetic_expression(self):
        """Gets the synthetic_expression of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The synthetic_expression of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: str
        """
        return self._synthetic_expression

    @synthetic_expression.setter
    def synthetic_expression(self, synthetic_expression):
        """Sets the synthetic_expression of this IndicatorDtoIncludeMetadata.


        :param synthetic_expression: The synthetic_expression of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: str
        """

        self._synthetic_expression = synthetic_expression

    @property
    def evaluation_order(self):
        """Gets the evaluation_order of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The evaluation_order of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: int
        """
        return self._evaluation_order

    @evaluation_order.setter
    def evaluation_order(self, evaluation_order):
        """Sets the evaluation_order of this IndicatorDtoIncludeMetadata.


        :param evaluation_order: The evaluation_order of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: int
        """

        self._evaluation_order = evaluation_order

    @property
    def extended_info(self):
        """Gets the extended_info of this IndicatorDtoIncludeMetadata.  # noqa: E501


        :return: The extended_info of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._extended_info

    @extended_info.setter
    def extended_info(self, extended_info):
        """Sets the extended_info of this IndicatorDtoIncludeMetadata.


        :param extended_info: The extended_info of this IndicatorDtoIncludeMetadata.  # noqa: E501
        :type: dict(str, str)
        """

        self._extended_info = extended_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndicatorDtoIncludeMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndicatorDtoIncludeMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
