# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MaintenanceWindowDeviceGroupDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'notes': 'str',
        'maintenance_type': 'str',
        'schedule_instance': 'ScheduleInstanceDto',
        'actions': 'str',
        'mapped_entities': 'list[MappedDeviceGroupEntityDto]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'notes': 'notes',
        'maintenance_type': 'maintenanceType',
        'schedule_instance': 'scheduleInstance',
        'actions': 'actions',
        'mapped_entities': 'mappedEntities'
    }

    def __init__(self, id='Maintenance window UUID -- omit to auto-generate for POST or leave unchanged for PUT', name='Name of maintenance window -- must be unique', notes='Free form notes', maintenance_type='Type of maintenance window', schedule_instance=None, actions='List of actions for this maintenance window -- SUPPRESS_ALERT_NOTIFICATIONS (SevOne will not send notification emails or traps for alerts occurring during this maintenance window), CATEGORIZE_ALERTS (Prepend "Maintenance Window" to alerts overlapping this maintenance window and downgrade severity levels higher than Info), EXCLUDE_DATA_FROM_BASELINES (Exclude data during the maintenance window from baseline calculations), EXCLUDE_DATA_FROM_AGGREGATION (Exclude data during the maintenance window from aggregation calculations)', mapped_entities=None):  # noqa: E501
        """MaintenanceWindowDeviceGroupDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._notes = None
        self._maintenance_type = None
        self._schedule_instance = None
        self._actions = None
        self._mapped_entities = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if notes is not None:
            self.notes = notes
        if maintenance_type is not None:
            self.maintenance_type = maintenance_type
        self.schedule_instance = schedule_instance
        if actions is not None:
            self.actions = actions
        if mapped_entities is not None:
            self.mapped_entities = mapped_entities

    @property
    def id(self):
        """Gets the id of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The id of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MaintenanceWindowDeviceGroupDto.


        :param id: The id of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The name of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MaintenanceWindowDeviceGroupDto.


        :param name: The name of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The notes of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this MaintenanceWindowDeviceGroupDto.


        :param notes: The notes of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def maintenance_type(self):
        """Gets the maintenance_type of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The maintenance_type of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: str
        """
        return self._maintenance_type

    @maintenance_type.setter
    def maintenance_type(self, maintenance_type):
        """Sets the maintenance_type of this MaintenanceWindowDeviceGroupDto.


        :param maintenance_type: The maintenance_type of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["PLANNED"]  # noqa: E501
        if maintenance_type not in allowed_values:
            raise ValueError(
                "Invalid value for `maintenance_type` ({0}), must be one of {1}"  # noqa: E501
                .format(maintenance_type, allowed_values)
            )

        self._maintenance_type = maintenance_type

    @property
    def schedule_instance(self):
        """Gets the schedule_instance of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The schedule_instance of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: ScheduleInstanceDto
        """
        return self._schedule_instance

    @schedule_instance.setter
    def schedule_instance(self, schedule_instance):
        """Sets the schedule_instance of this MaintenanceWindowDeviceGroupDto.


        :param schedule_instance: The schedule_instance of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: ScheduleInstanceDto
        """
        if schedule_instance is None:
            raise ValueError("Invalid value for `schedule_instance`, must not be `None`")  # noqa: E501

        self._schedule_instance = schedule_instance

    @property
    def actions(self):
        """Gets the actions of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The actions of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: str
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this MaintenanceWindowDeviceGroupDto.


        :param actions: The actions of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["SUPPRESS_ALERT_NOTIFICATIONS,CATEGORIZE_ALERTS,EXCLUDE_DATA_FROM_BASELINES,EXCLUDE_DATA_FROM_AGGREGATION"]  # noqa: E501
        if actions not in allowed_values:
            raise ValueError(
                "Invalid value for `actions` ({0}), must be one of {1}"  # noqa: E501
                .format(actions, allowed_values)
            )

        self._actions = actions

    @property
    def mapped_entities(self):
        """Gets the mapped_entities of this MaintenanceWindowDeviceGroupDto.  # noqa: E501


        :return: The mapped_entities of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :rtype: list[MappedDeviceGroupEntityDto]
        """
        return self._mapped_entities

    @mapped_entities.setter
    def mapped_entities(self, mapped_entities):
        """Sets the mapped_entities of this MaintenanceWindowDeviceGroupDto.


        :param mapped_entities: The mapped_entities of this MaintenanceWindowDeviceGroupDto.  # noqa: E501
        :type: list[MappedDeviceGroupEntityDto]
        """

        self._mapped_entities = mapped_entities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MaintenanceWindowDeviceGroupDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaintenanceWindowDeviceGroupDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
