# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PerformanceMetricsSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'raw_data': 'RawDataSettings',
        'source_fields': 'SourceFieldsSetting'
    }

    attribute_map = {
        'raw_data': 'rawData',
        'source_fields': 'sourceFields'
    }

    def __init__(self, raw_data=None, source_fields=None):  # noqa: E501
        """PerformanceMetricsSettings - a model defined in Swagger"""  # noqa: E501
        self._raw_data = None
        self._source_fields = None
        self.discriminator = None
        self.raw_data = raw_data
        if source_fields is not None:
            self.source_fields = source_fields

    @property
    def raw_data(self):
        """Gets the raw_data of this PerformanceMetricsSettings.  # noqa: E501


        :return: The raw_data of this PerformanceMetricsSettings.  # noqa: E501
        :rtype: RawDataSettings
        """
        return self._raw_data

    @raw_data.setter
    def raw_data(self, raw_data):
        """Sets the raw_data of this PerformanceMetricsSettings.


        :param raw_data: The raw_data of this PerformanceMetricsSettings.  # noqa: E501
        :type: RawDataSettings
        """
        if raw_data is None:
            raise ValueError("Invalid value for `raw_data`, must not be `None`")  # noqa: E501

        self._raw_data = raw_data

    @property
    def source_fields(self):
        """Gets the source_fields of this PerformanceMetricsSettings.  # noqa: E501


        :return: The source_fields of this PerformanceMetricsSettings.  # noqa: E501
        :rtype: SourceFieldsSetting
        """
        return self._source_fields

    @source_fields.setter
    def source_fields(self, source_fields):
        """Sets the source_fields of this PerformanceMetricsSettings.


        :param source_fields: The source_fields of this PerformanceMetricsSettings.  # noqa: E501
        :type: SourceFieldsSetting
        """

        self._source_fields = source_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PerformanceMetricsSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerformanceMetricsSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
