# coding: utf-8

"""
    SevOne API Documentation

    Supported endpoints by the new RESTful API  # noqa: E501

    OpenAPI spec version: 2.1.42, Hash: 719f8be
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.indicators_api import IndicatorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIndicatorsApi(unittest.TestCase):
    """IndicatorsApi unit test stubs"""

    def setUp(self):
        self.api = IndicatorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device_indicator_data(self):
        """Test case for create_device_indicator_data

        Create device indicator data  # noqa: E501
        """
        pass

    def test_create_device_indicator_data1(self):
        """Test case for create_device_indicator_data1

        Create device indicator data  # noqa: E501
        """
        pass

    def test_get_indicator(self):
        """Test case for get_indicator

        Get indicator by deviceId, objectId and indicatorId  # noqa: E501
        """
        pass

    def test_get_indicator1(self):
        """Test case for get_indicator1

        Get indicator by deviceId, objectId and indicatorId  # noqa: E501
        """
        pass

    def test_get_indicator_data(self):
        """Test case for get_indicator_data

        Get indicator data by deviceId, objectId and indicatorId  # noqa: E501
        """
        pass

    def test_get_indicator_data1(self):
        """Test case for get_indicator_data1

        Get indicator data by deviceId, objectId and indicatorId  # noqa: E501
        """
        pass

    def test_get_indicators(self):
        """Test case for get_indicators

        Get indicators by deviceId and objectId  # noqa: E501
        """
        pass

    def test_get_indicators1(self):
        """Test case for get_indicators1

        Get indicators by deviceId and objectId  # noqa: E501
        """
        pass

    def test_get_last_seen_timestamp_for_indicators(self):
        """Test case for get_last_seen_timestamp_for_indicators

        Get the timestamp of the most recent data point for indicators  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
